TERMUX_SUBPKG_INCLUDE="lib/libgomp.a.7.2 lib/gcc/${TERMUX_HOST_PLATFORM}/${TERMUX_PKG_VERSION}/include/omp.h.7.2" 
TERMUX_SUBPKG_DESCRIPTION="openmp library for gcc"
TERMUX_SUBPKG_DEPENDS="gcc-7"
TERMUX_PKG_KEEP_STATIC_LIBRARIES="true"
